name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Set env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
      # I don't want to keep this.
      # https://github.com/joepio/atomic-data-rust/issues/230
      - name: install dependencies
        run: sudo apt-get install libgtk-3-dev
      - name: Transfer binary rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "target/release/atomic-server"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ~/
      # - name: Export data
      #   run: ~/atomic-server --export
      # - name: Run new server
      #   run: ~/atomic-server &> log-${{ GITHUB_REF#refs/*/ }}
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: ~/atomic-server export && ~/atomic-server --ip 0.0.0.0 --https --domain atomicdata.dev --email joep@argu.co &> log-${{ env.RELEASE_VERSION }}
