name: Release (crates.io + binaries)

on:
  release:
    types: [created]
  workflow_dispatch:


jobs:
  crates:
    runs-on: ubuntu-latest
    steps:
    - name: publish crates
      uses: katyo/publish-crates@v1

  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          x86_64-pc-windows-gnu,
          x86_64-unknown-linux-musl,
          # Not working:
          # https://github.com/rust-build/rust-build.action/issues/11
          # x86_64-apple-darwin,
        ]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          # Rather have a plain binary if possible
          # EXTRA_FILES: "README.md LICENSE"
